[package]
name = "polars-ocaml-macros"
version.workspace = true
edition.workspace = true

[dependencies]
proc-macro2 = "^1.0.78"
syn = "^2.0.31"
quote = "^1.0.35"

[dev-dependencies]
expect-test = "1.4.1"
prettyplease = "0.2"

[lib]
proc-macro = true